CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(40) NOT NULL,
    description  varchar(500) NOT NULL,
    duration INTEGER NOT NULL,
    release_date date,
    rating varchar(40)
);


CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(100) NOT NULL,
    login varchar(50) NOT NULL,
    name  varchar(100) NOT NULL,
    birthday date NOT NULL
);


CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS film_genres (
    film_id INTEGER NOT NULL REFERENCES films (film_id) ON DELETE RESTRICT,
    genre_id INTEGER NOT NULL REFERENCES genres (genre_id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS film_likes (
    film_id INTEGER NOT NULL REFERENCES films (film_id) ON DELETE RESTRICT,
    user_id INTEGER NOT NULL REFERENCES users (user_id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS user_friendship (
    user_id INTEGER NOT NULL REFERENCES users (user_id) ON DELETE RESTRICT,
    friend_id INTEGER NOT NULL REFERENCES users (user_id) ON DELETE RESTRICT,
    accepted BOOLEAN NOT NULL DEFAULT FALSE
);